
POST http://localhost:3000/api/userModel
Content-Type: application/json

{
    "firstName":"kumaresh",
    "lastName":"V"
}

###

GET  https://hotels-com-provider.p.rapidapi.com/v1/hotels/booking-details
###
//https://railwaytesting.herokuapp.com
###

POST http://localhost:3000/flights/save
Content-Type: application/json

{
    "from":"Delhi",
    "to":"Australia",

    "Name":"Australia carrier",
    "AirlinesName":"Jet Airways",
    "DepartureTime":"21:20",
    "DestinationTime":"02:05",
    "TotalTime":22,
    "Fare":1500,
    "seats":20,

    "date":"26/05/2021",
    

    "type":"first class"
}

###
POST http://localhost:3000/flights/book
Content-Type: application/json

{
    "from":"Delhi",
    "to":"Australia",

    "date":"26/05/2021",
    

    "type":"first class"
}
###
POST https://railwaytesting.herokuapp.com/api/find/search
Content-Type: application/json

{
   "date":"26/05/2021"
}
###
POST https://railwaytesting.herokuapp.com/api/find/book
Content-Type: application/json

{
 "from":"Jammu",
    "to":"Gujarat",
   
    "date":"25/05/2021",
   
    "type":"General"

}

###


GET  http://localhost:3000/hotel/allhotels



###
POST http://localhost:3000/hotel/search
Content-Type: application/json

{

"Name":"Dubai Palace"

}

###

POST http://localhost:3000/hotel/new
Content-Type: application/json

{
"Hno":3,
"Name":"Good Hotel",
"Location":"Mumbai",
"Cost":4000,
"Totalrooms":{

    "Double":5,
    "Single":7,
    "Non-AC":3

},
"Availablerooms":{
"Double":5,
    "Single":7,
    "Non-AC":3
},
"Tags":["Free Parking",
"Swimming Pool ","Bonfire"]
,
"Bookingdetails":{

}

}

###
POST http://localhost:3000/hotel/book
Content-Type: application/json

{

"Hno":2,
"Name":"Dubai Palace",
"Location":"Mumbai",
"Cost":3000,

"Details":{
"Single":1
    
}


}


###
POST http://localhost:3000/bus/search
Content-Type: application/json

{

"from":"Haryana",
"to":"Bangalore",
"BusName":"Bangalore express",
"ArrivalTime":"08:00",
"DestinationTime":"16:00",
"seats":50,
"Fare":1600

}


###
POST http://localhost:3000/bus/save
Content-Type: application/json

{

"from":"Haryana",
"to":"Bangalore",
"BusName":"Bangalore express",
"ArrivalTime":"08:00",
"DestinationTime":"16:00",
"seats":50,
"Fare":1600,
"TotalTimeinhr":8,
"IntermediateStops":["stop1","stop2"],
"date":"26/05/2021",
"type":"Semi-Sleeper"

}


###
GET http://localhost:3000/bus/fetchall


###
POST http://localhost:3000/bus/book
Content-Type: application/json

{
"from":"Haryana",
"to":"Bangalore",
"BusName":"Bangalore express",
"ArrivalTime":"08:00",
"DestinationTime":"16:00",
"seats":50,
"Fare":1600,
"date":"26/05/2021",
"type":"Semi-Sleeper"

}














