
POST http://localhost:3000/api/userModel
Content-Type: application/json

{
    "firstName":"kumaresh",
    "lastName":"V"
}

###

GET  https://hotels-com-provider.p.rapidapi.com/v1/hotels/booking-details
###
//https://railwaytesting.herokuapp.com
###

POST http://localhost:3000/api/find/save
Content-Type: application/json

{
    "from":"x2",
    "to":"yy2",

    "name":"Jhh Express",
    "ArrivalTime":"21:20",
    "DestinationTime":"02:05",
    "TotalTime":22,
    "Fare":1300,
    

    "date":"26/05/2021",
    "seats":20,

    "type":"General"
}

###
POST https://railwaytesting.herokuapp.com/api/find/search
Content-Type: application/json

{
    
  "type":"General"
}
###
POST http://localhost:3000/api/find/book
Content-Type: application/json

{
 "from":"Jammu",
    "to":"Gujarat",
   
    "date":"25/05/2021",
   
    "type":"General"

}
