
POST http://localhost:3000/api/userModel
Content-Type: application/json

{
    "firstName":"kumaresh",
    "lastName":"V"
}

###

GET  https://hotels-com-provider.p.rapidapi.com/v1/hotels/booking-details
###
//https://railwaytesting.herokuapp.com
###

POST http://localhost:3000/flights/save
Content-Type: application/json

{
    "from":"Delhi",
    "to":"Australia",

    "Name":"Australia carrier",
    "AirlinesName":"Jet Airways",
    "DepartureTime":"21:20",
    "DestinationTime":"02:05",
    "TotalTime":22,
    "Fare":1500,
    "seats":20,

    "date":"26/05/2021",
    

    "type":"first class"
}

###
POST http://localhost:3000/flights/book
Content-Type: application/json

{"from": "USA",
    "to": "Australia",
    "date": "29/05/2021",
"id":"10022",
    "type":"first class"
}
###

GET http://localhost:3000/flights/fetchall


###
POST https://railwaytesting.herokuapp.com/api/find/search
Content-Type: application/json

{
   "date":"26/05/2021"
}
###
POST https://railwaytesting.herokuapp.com/api/find/book
Content-Type: application/json

{
 "from":"Jammu",
    "to":"Gujarat",
   
    "date":"25/05/2021",
   
    "type":"General"

}

###


GET  http://localhost:3000/hotel/allhotels



###
POST http://localhost:3000/hotel/search
Content-Type: application/json

{

    "name": "Mumbai Palace"
}

###

POST http://localhost:3000/hotel/new
Content-Type: application/json

{
"hno":3,
 "name":"Mumbai Palace",
"location":"Mumbai",
"cost":8000,

"totalrooms":[
{

    "type":"double",
    "available":40,
    "total":40

}

],

"tags":"Free Parking,Swimming Pool,Bonfire",
"images":""


}

###
POST http://localhost:3000/hotel/book
Content-Type: application/json

{

"hno":3,
 "name":"Mumbai Palace",
"location":"Mumbai",
"cost":8000,

"details":{
 "type":"double",
  "quantity":2
    
},
"id":"12589577885"


}


###
POST http://localhost:3000/bus/search
Content-Type: application/json

{

"from":"Haryana",
"to":"Bangalore",
"BusName":"Bangalore express",
"ArrivalTime":"08:00",
"DestinationTime":"16:00",
"seats":50,
"Fare":1600

}


###
POST http://localhost:3000/bus/book
Content-Type: application/json

{

"from":"loc1",
"to":"loc2",
"BusName":"loc express",
"ArrivalTime":"08:00",
"DestinationTime":"16:00",
"seats":50,
"Fare":1700,
"TotalTimeinhr":8,
"IntermediateStops":["stop1","stop2"],
"date":"26/05/2021",
"type":"Semi-Sleeper",
"id":"6385"
}


###
GET http://localhost:3000/api/find/fetchall


###
POST http://localhost:3000/api/find/book
Content-Type: application/json

{ "type": "Sleeper",
    "Bookingdetails": [],
    "id": "60ae",
    "from": "Chennai",
    "to": "Mumbai",
    "TrainName": "Mumbai Express",
    "ArrivalTime": "22:20",
    "DestinationTime": "12:00",
    "TotalTime": 8,
    "Fare": 800,
    "seats": 196,
    "date": "24/05/2021"
}


###
POST http://localhost:3000/travel/newtravel
Content-Type: application/json

{
"Pno":3,
"PackageName":"GOA Tour",
"Location":"GOA",
"Cost":25000,
"Description":{

"Day1":"Beaches",
"Day2":"Party",
"Day3":"Beach and show"


},
"TotalDays":3,
"Tags":["Boating","Touring","Goa"],
"Bookingdetails":{},
"BookCount":0

}
###
GET http://localhost:3000/travel/alltravel
###
POST http://localhost:3000/travel/bookingforuser
Content-Type: application/json

{
"id":"60af6b9226d9893621a7a78d"
}
###

POST http://localhost:3000/travel/book
Content-Type: application/json

{
"Pno":2,
"id":"60af6b9226d9893621a7a78d",
"PackageName":"GOA Tour",
"Location":"GOA",
"Cost":25000,
"Bookingdetails":{


    "No of persons":5,
    "Person1":{
        "Name":"user1",
        "Age":22
    },
     "Person2":{
        "Name":"user2",
        "Age":25
    },
    "StartDate":"26/05/2021",
    "EndDate":"29/05/2021"
}

}
###


POST http://localhost:3000/user/signup
Content-Type: application/json

{
"Username":"user5",
"Password":"password",
"Email":"user5@email.com"


}

###

POST https://railwaytesting.herokuapp.com/user/login
Content-Type: application/json

{
"Username":"Kumaresh",
"Password":"password"

}

###
GET http://localhost:3000/user/allusers
###
GET http://localhost:3000/user/searchuser
Content-Type: application/json

{
          "Username": "user2"

}


###

POST https://railwaytesting.herokuapp.com/travel/book
Content-Type: application/json

{
"Pno":2,
"PackageName":"GOA Tour",
"Location":"GOA",
"Cost":25000,
"Bookingdetails":{

"No of persons":2,
"Person1":{
"Name":"Kumaresh",
"Age":22
},
"Person2":{
"Name":"Saresh",
"Age":25
},
"StartDate":"26/05/2021",
"EndDate":"29/05/2021"
}

}
###


POST https://railwaytesting.herokuapp.com/travel/search
Content-Type: application/json

{
"Pno":1,
"PackageName":"Boat Tour",
"Location":"Maldives",
"Cost":15000  }

###
GET https://railwaytesting.herokuapp.com/travel/alltravel

###

POST https://railwaytesting.herokuapp.com/travel/newtravel

{
"Pno":5,
"PackageName":"GOA Tour",
"Location":"GOA",
"Cost":25000,
"Description":{

"Day1":"Beaches",
"Day2":"Party",
"Day3":"Beach and show"

},
"TotalDays":3,
"Tags":["Boating","Touring","Goa"],
"Bookingdetails":{},
"BookCount":0

}

###


POST http://localhost:3000/hotel/bookingforuser
Content-Type: application/json

{
    
"id":"1111"

}